### ISSUE TITLE
Project is missing lincense information

### ISSUE THREAD

**Issue by svelue** [VarunSaiTeja/Graph.ArgumentValidator#10]
I can not find any licensing information for this project. This is important to be able to use it legally: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Please add licensing information, I would propose to use the MIT License as it is quite common for open source software: https://opensource.org/license/mit

**Comment by VarunSaiTeja** [comment]
Thanks @svelue .
Added MIT LICENSE
